baseurl = "/"
title = ""

languagecode = "en"
defaultcontentlanguage = "en"

pagination.pagerSize = 20
canonifyurls = true

ignoreFiles = [ "\\.qmd$", "\\.ipynb$", "\\.py$" ]
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "manni"   # Chroma Style Gallery https://xyproto.github.io/splash/docs/longer/all.html

[params]
 repourl = "https://github.com/WestDRI/wgpages"
 info = "Various courses"
 sfuavatar = "/img/sfu.png"
 dracavatar = "/img/drac.png"
 favicon_32 = "/img/sfu_favicon.png"
 footercontent = ""
 dateformat = "January 2, 2006"
 hideCredits = false
 hideCopyright = false
 since = 2021

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]
